{% set name = "nushell" %}
{% set version = "0.95.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: f41a0f41af3996581f9bd485cfe5d55f26dd486dc3812b386bd43439c72a6d16

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
  host:
    - zlib
    - openssl

test:
  commands:
    - nu --version
    - nu --help

about:
  home: https://nushell.sh
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: A new type of shell
  dev_url: https://github.com/nushell/nushell

extra:
  recipe-maintainers:
    - pavelzw
