{% set name = "nushell" %}
{% set version = "0.103.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0e654e47627ad8c053350bbc25fa75c55b76e11fd6841118214eaa5a10f9686e

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
  host:
    - zlib
    - openssl

test:
  commands:
    - nu --version
    - nu --help

about:
  home: https://nushell.sh
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: A new type of shell
  dev_url: https://github.com/nushell/nushell

extra:
  recipe-maintainers:
    - thebigdalt
    - pavelzw
