{% set name = "nushell" %}
{% set version = "0.97.1" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: e605d5a7f104b7f2bf99197ca2f34a4a68f68cc12ecab41f606113e6a65b67b1

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
  host:
    - zlib
    - openssl

test:
  commands:
    - nu --version
    - nu --help

about:
  home: https://nushell.sh
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: A new type of shell
  dev_url: https://github.com/nushell/nushell

extra:
  recipe-maintainers:
    - pavelzw
