{% set name = "nushell" %}
{% set version = "0.100.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 00b94984d3140e286e06d4beca2926ef80e0a0cc3ada75916e4fb9fa66ec28ad

build:
  number: 1

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
  host:
    - zlib
    - openssl

test:
  commands:
    - nu --version
    - nu --help

about:
  home: https://nushell.sh
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: A new type of shell
  dev_url: https://github.com/nushell/nushell

extra:
  recipe-maintainers:
    - thebigdalt
    - pavelzw
