context:
  version: "0.110.0"

package:
  name: nushell
  version: ${{ version }}

source:
  url: https://github.com/nushell/nushell/archive/16cfe2a70cbc1fae6e7bc7fba284b6748c7c91f5.zip
  sha256: a49c07fdc73c331e172a0a738bd6f164efec6d1431c6769618be93def685588b
  # url: https://github.com/nushell/nushell/archive/refs/tags/${{ version }}.tar.gz
  # sha256: e4c95f743cea3d985ab90e03fd35707a46eef926d407ed363f994155c1ca5055
  patches:
    - 0001-fix-env-nu-lib-dirs.patch

build:
  number: 2
  script: build.nu
  # https://github.com/prefix-dev/rattler-build/issues/2133
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - nushell # script dependency
  host:
    - zlib
    - openssl
    - if: osx
      then: libgit2

tests:
  - package_contents:
      strict: true
      files:
        - bin/nu_plugin_*
        - etc/pixi/nu/global-ignore-conda-prefix
        # https://github.com/prefix-dev/rattler-build/issues/2133
        - etc/conda/env_vars.d/nushell.json
      bin:
        - nu
  - script:
      - if: unix
        then: nu -c 'print ($NU_LIB_DIRS)'
        else: nu -c "print ($NU_LIB_DIRS)"
      - nu --version
      - nu --help
      - if: unix
        then:
          - mkdir -p $CONDA_PREFIX/share/nushell/lib
          - echo "export def hi [] { \"foo\" }" > $CONDA_PREFIX/share/nushell/lib/foo.nu
        else:
          - mkdir %CONDA_PREFIX%\share\nushell\lib
          - echo export def hi [] { "foo" }> %CONDA_PREFIX%\share\nushell\lib\foo.nu
      - nu -c "use foo.nu hi; hi"

about:
  homepage: https://nushell.sh
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A new type of shell
  repository: https://github.com/nushell/nushell

extra:
  recipe-maintainers:
    - thebigdalt
    - pavelzw
