context:
  version: "0.111.0"

package:
  name: nushell
  version: ${{ version }}

source:
  url: https://github.com/nushell/nushell/archive/refs/tags/${{ version }}.tar.gz
  sha256: e3a7980bb5532016036d9fdbbe0a2acc5a73f9549d1842ff6c8c0de2a6d1ddbe
  patches:
    # https://github.com/nushell/nushell/pull/17563
    - 0001-fix-env-nu-lib-dirs.patch

build:
  number: 0
  script: build.nu
  # https://github.com/prefix-dev/rattler-build/issues/2133
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - nushell # script dependency
  host:
    - zlib
    - openssl
    - if: osx
      then: libgit2

tests:
  - package_contents:
      strict: true
      bin:
        - nu
      files:
        - bin/nu_plugin_*
        - etc/pixi/nu/global-ignore-conda-prefix
        # https://github.com/prefix-dev/rattler-build/issues/2133
        - if: not win
          then: etc/conda/env_vars.d/nushell.json
          else:
            - etc/conda/activate.d/nushell_activate.bat
            - etc/conda/activate.d/nushell_activate.sh
            - etc/conda/deactivate.d/nushell_deactivate.bat
            - etc/conda/deactivate.d/nushell_deactivate.sh
  - script:
      - if: unix
        then: nu -c 'print ($NU_LIB_DIRS)'
        else: nu -c "print ($NU_LIB_DIRS)"
      - nu --version
      - nu --help
      - if: unix
        then:
          - mkdir -p $CONDA_PREFIX/share/nushell/lib
          - echo "export def hi [] { \"foo\" }" > $CONDA_PREFIX/share/nushell/lib/foo.nu
        else:
          - mkdir %CONDA_PREFIX%\share\nushell\lib
          - echo export def hi [] { "foo" }> %CONDA_PREFIX%\share\nushell\lib\foo.nu
      - nu -c "use foo.nu hi; hi"

about:
  homepage: https://nushell.sh
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A new type of shell
  repository: https://github.com/nushell/nushell

extra:
  recipe-maintainers:
    - thebigdalt
    - pavelzw
