context:
  version: "0.110.0"

package:
  name: nushell
  version: ${{ version }}

source:
  url: https://github.com/nushell/nushell/archive/refs/tags/${{ version }}.tar.gz
  sha256: e4c95f743cea3d985ab90e03fd35707a46eef926d407ed363f994155c1ca5055

build:
  number: 1
  script: build.nu
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - nushell # script dependency
  host:
    - zlib
    - openssl

tests:
  - script:
      - nu --version
      - nu --help

about:
  homepage: https://nushell.sh
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: A new type of shell
  repository: https://github.com/nushell/nushell

extra:
  recipe-maintainers:
    - thebigdalt
    - pavelzw
