context:
  version: "0.110.0"

package:
  name: nushell
  version: ${{ version }}

source:
  url: https://github.com/nushell/nushell/archive/refs/tags/${{ version }}.tar.gz
  sha256: e4c95f743cea3d985ab90e03fd35707a46eef926d407ed363f994155c1ca5055

build:
  number: 2
  script: build.nu
  # https://github.com/prefix-dev/rattler-build/issues/2133
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - nushell # script dependency
  host:
    - zlib
    - openssl
    - if: osx
      then: libgit2

tests:
  - package_contents:
      strict: true
      files:
        - bin/nu_plugin_*
        - etc/pixi/nu/global-ignore-conda-prefix
        - share/nushell/vendor/autoload/set-nu-lib-dirs.nu
        - etc/conda/test-files/nushell/0/test-nu.nu
        # https://github.com/prefix-dev/rattler-build/issues/2133
        - etc/conda/env_vars.d/nushell.json
      bin:
        - nu
  - files:
      recipe:
        - test-nu.nu
    script:
      - if: unix
        then: nu -c 'print ($nu.vendor-autoload-dirs)'
        else: nu -c "print ($nu.vendor-autoload-dirs)"
      - nu --version
      - nu --help
      - nu -l test-nu.nu

about:
  homepage: https://nushell.sh
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A new type of shell
  repository: https://github.com/nushell/nushell

extra:
  recipe-maintainers:
    - thebigdalt
    - pavelzw
